apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /nginx/var;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /runtime-config/ {
        alias /nginx/var/runtime-config/;
        add_header Cache-Control "no-store";
      }

      location ~ ^/api/?(.*)$ {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://backend-svc:8000/$1;
      }

      location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_pass http://backend-svc:8000;
      }
    }
